### ISSUE TITLE
Add Project Board

### ISSUE THREAD

**Issue by luqmansen** [sayyidyofa/WolframBot#2]
Add agile project board for this repo, use predefined template (Kanban) or create custom one

**Comment by sayyidyofa** [comment]
Noted and assigned the task to team member. After the project board is completed a new issue will be created "Maintaining the Project Board" if seen necessary. This issue will be closed when a project board is built.

**Comment by luqmansen** [comment]
no

**Comment by luqmansen** [comment]
only repo owner allowed to do that

**Comment by sayyidyofa** [comment]
well then there'll be no project board. this issue will be closed
